version: "3.7"

networks:
  first-network:
    name: ${COMPOSE_PROJECT_NAME}-network

services:

    mysql:
      image: mysql:8.0.16
      container_name: ${COMPOSE_PROJECT_NAME}-mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: unless-stopped
      networks:
        - first-network
      volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/my.cnf:/etc/mysql/conf.d/project.cnf
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_DATABASE=${DB_DATABASE:?}
        - MYSQL_USER=${DB_USERNAME:?}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_HOST=%
      ports:
        - "${DB_PORT:-3356}:3306"

    php-fpm:
      build: ./php-fpm
      container_name: ${COMPOSE_PROJECT_NAME}-php-fpm
      restart: unless-stopped
      working_dir: /app
      networks:
        - first-network
      volumes:
        - ../:/app:delegated
        - /app/docker

    webserver:
      image: nginx:1.17
      container_name: ${COMPOSE_PROJECT_NAME}-webserver
      restart: unless-stopped
      depends_on:
        - php-fpm
        - mysql
      networks:
        - first-network
      volumes:
          - ../public:/app/public
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./nginx/logs:/var/log/nginx
      ports:
       - "${APP_PORT:-8090}:80"
